### ISSUE TITLE
$imageDialog.openModal is not a function

### ISSUE THREAD

**Issue by M-Blobby** [Cerealkillerway/materialNote#21]
Hi,

When I click on the icon for add a picture, I catch this error :

materialNote.js:5336 Uncaught TypeError: $imageDialog.openModal is not a function
    at Object.<anonymous> (http://127.0.0.1:81/js/materialNote.js:5336:22)
    at Function.Deferred (http://127.0.0.1:81/js/jquery.min.js:2:28973)
    at ImageDialog.showImageDialog (http://127.0.0.1:81/js/materialNote.js:5329:16)
    at ImageDialog.show (http://127.0.0.1:81/js/materialNote.js:5306:12)
    at HTMLDivElement.showImageDialog (http://127.0.0.1:81/js/materialNote.js:5531:29)
    at HTMLDivElement.hToolbarAndPopoverClick (http://127.0.0.1:81/js/materialNote.js:5632:31)
    at HTMLDivElement.dispatch (http://127.0.0.1:81/js/jquery.min.js:3:7537)
    at HTMLDivElement.r.handle (http://127.0.0.1:81/js/jquery.min.js:3:5620)

Same with icons for link and help.
The version of my lib Materializecss is 0.97.8, not sure it can help...

Thank you for your help.

**Comment by nicolasbonnici** [comment]
You can take a look at this PR to solve your issue: https://github.com/Cerealkillerway/materialNote/pull/30

The materialize modal plugin was updated in 0.97.8

**Comment by M-Blobby** [comment]
Hi,

Sorry for my late answer, but it seems to be good with your fix !

Thanks a lot :).
